
package tr.com.yurticikargo.sswintegrationservices;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WsReportWithReferenceServices", targetNamespace = "http://yurticikargo.com.tr/sswIntegrationServices")
@XmlSeeAlso({
    tr.com.yurticikargo.sswintegrationservices.ObjectFactory.class,
    tr.com.yurticikargo.wsexceptions.ObjectFactory.class
})
public interface WsReportWithReferenceServices {


    /**
     * 
     * @param password
     * @param dateType
     * @param endDate
     * @param subCustomer
     * @param custDocNumber
     * @param custId
     * @param language
     * @param userName
     * @param startDate
     * @return
     *     returns tr.com.yurticikargo.sswintegrationservices.DeliveryCollectionDataResponseVO
     * @throws YurticikargoWSException
     */
    @WebMethod
    @WebResult(name = "DeliveryCollectionDataResponseVO", targetNamespace = "")
    @RequestWrapper(localName = "getDeliveryCollectionInfoByReference", targetNamespace = "http://yurticikargo.com.tr/sswIntegrationServices", className = "tr.com.yurticikargo.sswintegrationservices.GetDeliveryCollectionInfoByReference")
    @ResponseWrapper(localName = "getDeliveryCollectionInfoByReferenceResponse", targetNamespace = "http://yurticikargo.com.tr/sswIntegrationServices", className = "tr.com.yurticikargo.sswintegrationservices.GetDeliveryCollectionInfoByReferenceResponse")
    public DeliveryCollectionDataResponseVO getDeliveryCollectionInfoByReference(
            @WebParam(name = "userName", targetNamespace = "")
                    String userName,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "language", targetNamespace = "")
                    String language,
            @WebParam(name = "startDate", targetNamespace = "")
                    String startDate,
            @WebParam(name = "endDate", targetNamespace = "")
                    String endDate,
            @WebParam(name = "dateType", targetNamespace = "")
                    String dateType,
            @WebParam(name = "custDocNumber", targetNamespace = "")
                    List<String> custDocNumber,
            @WebParam(name = "custId", targetNamespace = "")
                    List<Long> custId,
            @WebParam(name = "subCustomer", targetNamespace = "")
                    String subCustomer)
        throws YurticikargoWSException
    ;

    /**
     * 
     * @param password
     * @param endDate
     * @param custParamsVO
     * @param unitParamsVO
     * @param withCargoLifecycle
     * @param language
     * @param dateParamType
     * @param userName
     * @param wsUserGroupId
     * @param startDate
     * @param subCustomerFlag
     * @return
     *     returns tr.com.yurticikargo.sswintegrationservices.ShippingDataV3ResponseVO
     * @throws YurticikargoWSException
     */
    @WebMethod
    @WebResult(name = "ShippingDataV3ResponseVO", targetNamespace = "")
    @RequestWrapper(localName = "listInvDocumentByCustIdV2", targetNamespace = "http://yurticikargo.com.tr/sswIntegrationServices", className = "tr.com.yurticikargo.sswintegrationservices.ListInvDocumentByCustIdV2")
    @ResponseWrapper(localName = "listInvDocumentByCustIdV2Response", targetNamespace = "http://yurticikargo.com.tr/sswIntegrationServices", className = "tr.com.yurticikargo.sswintegrationservices.ListInvDocumentByCustIdV2Response")
    public ShippingDataV3ResponseVO listInvDocumentByCustIdV2(
            @WebParam(name = "userName", targetNamespace = "")
                    String userName,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "language", targetNamespace = "")
                    String language,
            @WebParam(name = "custParamsVO", targetNamespace = "")
                    CustParamsVO custParamsVO,
            @WebParam(name = "unitParamsVO", targetNamespace = "")
                    UnitParamsVO unitParamsVO,
            @WebParam(name = "subCustomerFlag", targetNamespace = "")
                    String subCustomerFlag,
            @WebParam(name = "startDate", targetNamespace = "")
                    String startDate,
            @WebParam(name = "endDate", targetNamespace = "")
                    String endDate,
            @WebParam(name = "dateParamType", targetNamespace = "")
                    String dateParamType,
            @WebParam(name = "wsUserGroupId", targetNamespace = "")
                    String wsUserGroupId,
            @WebParam(name = "withCargoLifecycle", targetNamespace = "")
                    String withCargoLifecycle)
        throws YurticikargoWSException
    ;

    /**
     * 
     * @param fieldValueArray
     * @param password
     * @param fieldName
     * @param endDate
     * @param custParamsVO
     * @param withCargoLifecycle
     * @param language
     * @param dateParamType
     * @param userName
     * @param startDate
     * @return
     *     returns tr.com.yurticikargo.sswintegrationservices.ShippingDataResponseVO
     * @throws YurticikargoWSException
     */
    @WebMethod
    @WebResult(name = "ShippingDataResponseVO", targetNamespace = "")
    @RequestWrapper(localName = "listInvDocumentByGrpSpecialField", targetNamespace = "http://yurticikargo.com.tr/sswIntegrationServices", className = "tr.com.yurticikargo.sswintegrationservices.ListInvDocumentByGrpSpecialField")
    @ResponseWrapper(localName = "listInvDocumentByGrpSpecialFieldResponse", targetNamespace = "http://yurticikargo.com.tr/sswIntegrationServices", className = "tr.com.yurticikargo.sswintegrationservices.ListInvDocumentByGrpSpecialFieldResponse")
    public ShippingDataResponseVO listInvDocumentByGrpSpecialField(
            @WebParam(name = "userName", targetNamespace = "")
                    String userName,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "language", targetNamespace = "")
                    String language,
            @WebParam(name = "custParamsVO", targetNamespace = "")
                    CustParamsVO custParamsVO,
            @WebParam(name = "fieldName", targetNamespace = "")
                    String fieldName,
            @WebParam(name = "fieldValueArray", targetNamespace = "")
                    List<String> fieldValueArray,
            @WebParam(name = "startDate", targetNamespace = "")
                    String startDate,
            @WebParam(name = "endDate", targetNamespace = "")
                    String endDate,
            @WebParam(name = "dateParamType", targetNamespace = "")
                    String dateParamType,
            @WebParam(name = "withCargoLifecycle", targetNamespace = "")
                    String withCargoLifecycle)
        throws YurticikargoWSException
    ;

    /**
     * 
     * @param password
     * @param endDate
     * @param custParamsVO
     * @param withCargoLifecycle
     * @param language
     * @param waybillNoArray
     * @param dateParamType
     * @param userName
     * @param startDate
     * @return
     *     returns tr.com.yurticikargo.sswintegrationservices.ShippingDataResponseVO
     * @throws YurticikargoWSException
     */
    @WebMethod
    @WebResult(name = "ShippingDataResponseVO", targetNamespace = "")
    @RequestWrapper(localName = "listInvDocumentByWaybillNo", targetNamespace = "http://yurticikargo.com.tr/sswIntegrationServices", className = "tr.com.yurticikargo.sswintegrationservices.ListInvDocumentByWaybillNo")
    @ResponseWrapper(localName = "listInvDocumentByWaybillNoResponse", targetNamespace = "http://yurticikargo.com.tr/sswIntegrationServices", className = "tr.com.yurticikargo.sswintegrationservices.ListInvDocumentByWaybillNoResponse")
    public ShippingDataResponseVO listInvDocumentByWaybillNo(
            @WebParam(name = "userName", targetNamespace = "")
                    String userName,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "language", targetNamespace = "")
                    String language,
            @WebParam(name = "custParamsVO", targetNamespace = "")
                    CustParamsVO custParamsVO,
            @WebParam(name = "waybillNoArray", targetNamespace = "")
                    List<String> waybillNoArray,
            @WebParam(name = "startDate", targetNamespace = "")
                    String startDate,
            @WebParam(name = "endDate", targetNamespace = "")
                    String endDate,
            @WebParam(name = "dateParamType", targetNamespace = "")
                    String dateParamType,
            @WebParam(name = "withCargoLifecycle", targetNamespace = "")
                    String withCargoLifecycle)
        throws YurticikargoWSException
    ;

    /**
     * 
     * @param fieldValueArray
     * @param password
     * @param fieldName
     * @param docIdArray
     * @param endDate
     * @param custParamsVO
     * @param withCargoLifecycle
     * @param language
     * @param dateParamType
     * @param userName
     * @param startDate
     * @return
     *     returns tr.com.yurticikargo.sswintegrationservices.ShippingDataResponseVO
     * @throws YurticikargoWSException
     */
    @WebMethod
    @WebResult(name = "ShippingDataResponseVO", targetNamespace = "")
    @RequestWrapper(localName = "listInvDocumentInterfaceByReference", targetNamespace = "http://yurticikargo.com.tr/sswIntegrationServices", className = "tr.com.yurticikargo.sswintegrationservices.ListInvDocumentInterfaceByReference")
    @ResponseWrapper(localName = "listInvDocumentInterfaceByReferenceResponse", targetNamespace = "http://yurticikargo.com.tr/sswIntegrationServices", className = "tr.com.yurticikargo.sswintegrationservices.ListInvDocumentInterfaceByReferenceResponse")
    public ShippingDataResponseVO listInvDocumentInterfaceByReference(
            @WebParam(name = "userName", targetNamespace = "")
                    String userName,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "language", targetNamespace = "")
                    String language,
            @WebParam(name = "custParamsVO", targetNamespace = "")
                    CustParamsVO custParamsVO,
            @WebParam(name = "fieldName", targetNamespace = "")
                    String fieldName,
            @WebParam(name = "fieldValueArray", targetNamespace = "")
                    List<String> fieldValueArray,
            @WebParam(name = "docIdArray", targetNamespace = "")
                    List<String> docIdArray,
            @WebParam(name = "startDate", targetNamespace = "")
                    String startDate,
            @WebParam(name = "endDate", targetNamespace = "")
                    String endDate,
            @WebParam(name = "dateParamType", targetNamespace = "")
                    String dateParamType,
            @WebParam(name = "withCargoLifecycle", targetNamespace = "")
                    String withCargoLifecycle)
        throws YurticikargoWSException
    ;

    /**
     * 
     * @param password
     * @param fieldName
     * @param endDate
     * @param custParamsVO
     * @param departureUnitId
     * @param language
     * @param dateParamType
     * @param userName
     * @param startDate
     * @return
     *     returns tr.com.yurticikargo.sswintegrationservices.ShippingDataV2ResponseVO
     * @throws YurticikargoWSException
     */
    @WebMethod
    @WebResult(name = "ShippingDataResponseVO", targetNamespace = "")
    @RequestWrapper(localName = "listInvDocumentInterfaceWithFailedDeliveryV2", targetNamespace = "http://yurticikargo.com.tr/sswIntegrationServices", className = "tr.com.yurticikargo.sswintegrationservices.ListInvDocumentInterfaceWithFailedDeliveryV2")
    @ResponseWrapper(localName = "listInvDocumentInterfaceWithFailedDeliveryV2Response", targetNamespace = "http://yurticikargo.com.tr/sswIntegrationServices", className = "tr.com.yurticikargo.sswintegrationservices.ListInvDocumentInterfaceWithFailedDeliveryV2Response")
    public ShippingDataV2ResponseVO listInvDocumentInterfaceWithFailedDeliveryV2(
            @WebParam(name = "userName", targetNamespace = "")
                    String userName,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "language", targetNamespace = "")
                    String language,
            @WebParam(name = "custParamsVO", targetNamespace = "")
                    CustParamsVO custParamsVO,
            @WebParam(name = "fieldName", targetNamespace = "")
                    String fieldName,
            @WebParam(name = "departureUnitId", targetNamespace = "")
                    String departureUnitId,
            @WebParam(name = "startDate", targetNamespace = "")
                    String startDate,
            @WebParam(name = "endDate", targetNamespace = "")
                    String endDate,
            @WebParam(name = "dateParamType", targetNamespace = "")
                    String dateParamType)
        throws YurticikargoWSException
    ;

    /**
     * 
     * @param fieldValueArray
     * @param password
     * @param fieldName
     * @param docIdArray
     * @param endDate
     * @param custParamsVO
     * @param withCargoLifecycle
     * @param language
     * @param dateParamType
     * @param userName
     * @param startDate
     * @return
     *     returns tr.com.yurticikargo.sswintegrationservices.XShippingV2ResponseVO
     * @throws YurticikargoWSException
     */
    @WebMethod
    @WebResult(name = "XShippingV2ResponseVO", targetNamespace = "")
    @RequestWrapper(localName = "listNgiShipping", targetNamespace = "http://yurticikargo.com.tr/sswIntegrationServices", className = "tr.com.yurticikargo.sswintegrationservices.ListNgiShipping")
    @ResponseWrapper(localName = "listNgiShippingResponse", targetNamespace = "http://yurticikargo.com.tr/sswIntegrationServices", className = "tr.com.yurticikargo.sswintegrationservices.ListNgiShippingResponse")
    public XShippingV2ResponseVO listNgiShipping(
            @WebParam(name = "userName", targetNamespace = "")
                    String userName,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "language", targetNamespace = "")
                    String language,
            @WebParam(name = "custParamsVO", targetNamespace = "")
                    CustParamsVO custParamsVO,
            @WebParam(name = "fieldName", targetNamespace = "")
                    String fieldName,
            @WebParam(name = "fieldValueArray", targetNamespace = "")
                    List<String> fieldValueArray,
            @WebParam(name = "docIdArray", targetNamespace = "")
                    List<String> docIdArray,
            @WebParam(name = "startDate", targetNamespace = "")
                    String startDate,
            @WebParam(name = "endDate", targetNamespace = "")
                    String endDate,
            @WebParam(name = "dateParamType", targetNamespace = "")
                    String dateParamType,
            @WebParam(name = "withCargoLifecycle", targetNamespace = "")
                    String withCargoLifecycle)
        throws YurticikargoWSException
    ;

}
