
package tr.com.yurticikargo.shippingorderdispatcherservices;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ShippingOrderDispatcherServices", targetNamespace = "http://yurticikargo.com.tr/ShippingOrderDispatcherServices")
@XmlSeeAlso({
    tr.com.yurticikargo.shippingorderdispatcherservices.ObjectFactory.class,
    tr.com.yurticikargo.wsexceptions.ObjectFactory.class
})
public interface ShippingOrderDispatcherServices {


    /**
     * 
     * @param returnCode
     * @param wsPassword
     * @param fieldName
     * @param wsUserName
     * @param wsLanguage
     * @return
     *     returns tr.com.yurticikargo.shippingorderdispatcherservices.ExtendedBaseResultVO
     * @throws YurticikargoWSException
     */
    @WebMethod
    @WebResult(name = "ExtendedBaseResultVO", targetNamespace = "")
    @RequestWrapper(localName = "cancelReturnShipmentCode", targetNamespace = "http://yurticikargo.com.tr/ShippingOrderDispatcherServices", className = "tr.com.yurticikargo.shippingorderdispatcherservices.CancelReturnShipmentCode")
    @ResponseWrapper(localName = "cancelReturnShipmentCodeResponse", targetNamespace = "http://yurticikargo.com.tr/ShippingOrderDispatcherServices", className = "tr.com.yurticikargo.shippingorderdispatcherservices.CancelReturnShipmentCodeResponse")
    public ExtendedBaseResultVO cancelReturnShipmentCode(
            @WebParam(name = "wsUserName", targetNamespace = "")
                    String wsUserName,
            @WebParam(name = "wsPassword", targetNamespace = "")
                    String wsPassword,
            @WebParam(name = "wsLanguage", targetNamespace = "")
                    String wsLanguage,
            @WebParam(name = "fieldName", targetNamespace = "")
                    String fieldName,
            @WebParam(name = "returnCode", targetNamespace = "")
                    String returnCode)
        throws YurticikargoWSException
    ;

    /**
     * 
     * @param wsPassword
     * @param cargoKeys
     * @param wsUserName
     * @param userLanguage
     * @return
     *     returns tr.com.yurticikargo.shippingorderdispatcherservices.ShippingCancelResultVO
     * @throws YurticikargoWSException
     */
    @WebMethod
    @WebResult(name = "ShippingOrderResultVO", targetNamespace = "")
    @RequestWrapper(localName = "cancelShipment", targetNamespace = "http://yurticikargo.com.tr/ShippingOrderDispatcherServices", className = "tr.com.yurticikargo.shippingorderdispatcherservices.CancelShipment")
    @ResponseWrapper(localName = "cancelShipmentResponse", targetNamespace = "http://yurticikargo.com.tr/ShippingOrderDispatcherServices", className = "tr.com.yurticikargo.shippingorderdispatcherservices.CancelShipmentResponse")
    public ShippingCancelResultVO cancelShipment(
            @WebParam(name = "wsUserName", targetNamespace = "")
                    String wsUserName,
            @WebParam(name = "wsPassword", targetNamespace = "")
                    String wsPassword,
            @WebParam(name = "userLanguage", targetNamespace = "")
                    String userLanguage,
            @WebParam(name = "cargoKeys", targetNamespace = "")
                    List<String> cargoKeys)
        throws YurticikargoWSException
    ;

    /**
     *
     * @param wsPassword
     * @param wsUserName
     * @param shippingOrderVO
     * @param userLanguage
     * @return
     *     returns tr.com.yurticikargo.shippingorderdispatcherservices.ShippingOrderResultVO
     * @throws YurticikargoWSException
     */
    @WebMethod
    @WebResult(name = "ShippingOrderResultVO", targetNamespace = "")
    @RequestWrapper(localName = "createShipmentDetail", targetNamespace = "http://yurticikargo.com.tr/ShippingOrderDispatcherServices", className = "tr.com.yurticikargo.shippingorderdispatcherservices.CreateShipmentDetail")
    @ResponseWrapper(localName = "createShipmentDetailResponse", targetNamespace = "http://yurticikargo.com.tr/ShippingOrderDispatcherServices", className = "tr.com.yurticikargo.shippingorderdispatcherservices.CreateShipmentDetailResponse")
    public ShippingOrderResultVO createShipmentDetail(
            @WebParam(name = "wsUserName", targetNamespace = "")
                    String wsUserName,
            @WebParam(name = "wsPassword", targetNamespace = "")
                    String wsPassword,
            @WebParam(name = "userLanguage", targetNamespace = "")
                    String userLanguage,
            @WebParam(name = "ShippingOrderVO", targetNamespace = "")
                    List<ShippingOrderCreateVO> shippingOrderVO)
        throws YurticikargoWSException
    ;

    /**
     *
     * @param wsPassword
     * @param wsUserName
     * @param shippingOrderVO
     * @param userLanguage
     * @return
     *     returns tr.com.yurticikargo.shippingorderdispatcherservices.ShippingOrderResultVO
     * @throws YurticikargoWSException
     */
    @WebMethod
    @WebResult(name = "ShippingOrderResultVO", targetNamespace = "")
    @RequestWrapper(localName = "createShipment", targetNamespace = "http://yurticikargo.com.tr/ShippingOrderDispatcherServices", className = "tr.com.yurticikargo.shippingorderdispatcherservices.CreateShipment")
    @ResponseWrapper(localName = "createShipmentResponse", targetNamespace = "http://yurticikargo.com.tr/ShippingOrderDispatcherServices", className = "tr.com.yurticikargo.shippingorderdispatcherservices.CreateShipmentResponse")
    public ShippingOrderResultVO createShipment(
            @WebParam(name = "wsUserName", targetNamespace = "")
                    String wsUserName,
            @WebParam(name = "wsPassword", targetNamespace = "")
                    String wsPassword,
            @WebParam(name = "userLanguage", targetNamespace = "")
                    String userLanguage,
            @WebParam(name = "ShippingOrderVO", targetNamespace = "")
                    List<ShippingOrderVO> shippingOrderVO)
            throws YurticikargoWSException
    ;

    /**
     * 
     * @param wsPassword
     * @param wsUserName
     * @param keys
     * @param onlyTracking
     * @param wsLanguage
     * @param keyType
     * @param addHistoricalData
     * @return
     *     returns tr.com.yurticikargo.shippingorderdispatcherservices.ShippingDeliveryResultVO
     * @throws YurticikargoWSException
     */
    @WebMethod
    @WebResult(name = "ShippingDeliveryVO", targetNamespace = "")
    @RequestWrapper(localName = "queryShipment", targetNamespace = "http://yurticikargo.com.tr/ShippingOrderDispatcherServices", className = "tr.com.yurticikargo.shippingorderdispatcherservices.QueryShipment")
    @ResponseWrapper(localName = "queryShipmentResponse", targetNamespace = "http://yurticikargo.com.tr/ShippingOrderDispatcherServices", className = "tr.com.yurticikargo.shippingorderdispatcherservices.QueryShipmentResponse")
    public ShippingDeliveryResultVO queryShipment(
            @WebParam(name = "wsUserName", targetNamespace = "")
                    String wsUserName,
            @WebParam(name = "wsPassword", targetNamespace = "")
                    String wsPassword,
            @WebParam(name = "wsLanguage", targetNamespace = "")
                    String wsLanguage,
            @WebParam(name = "keys", targetNamespace = "")
                    List<String> keys,
            @WebParam(name = "keyType", targetNamespace = "")
                    int keyType,
            @WebParam(name = "addHistoricalData", targetNamespace = "")
                    boolean addHistoricalData,
            @WebParam(name = "onlyTracking", targetNamespace = "")
                    boolean onlyTracking)
        throws YurticikargoWSException
    ;

    /**
     * 
     * @param wsPassword
     * @param jsonData
     * @param wsUserName
     * @param keys
     * @param onlyTracking
     * @param wsLanguage
     * @param keyType
     * @param addHistoricalData
     * @return
     *     returns tr.com.yurticikargo.shippingorderdispatcherservices.ShipmentDeliveryResultVO
     * @throws YurticikargoWSException
     */
    @WebMethod
    @WebResult(name = "ShipmentDeliveryResultVO", targetNamespace = "")
    @RequestWrapper(localName = "queryShipmentDetail", targetNamespace = "http://yurticikargo.com.tr/ShippingOrderDispatcherServices", className = "tr.com.yurticikargo.shippingorderdispatcherservices.QueryShipmentDetail")
    @ResponseWrapper(localName = "queryShipmentDetailResponse", targetNamespace = "http://yurticikargo.com.tr/ShippingOrderDispatcherServices", className = "tr.com.yurticikargo.shippingorderdispatcherservices.QueryShipmentDetailResponse")
    public ShipmentDeliveryResultVO queryShipmentDetail(
            @WebParam(name = "wsUserName", targetNamespace = "")
                    String wsUserName,
            @WebParam(name = "wsPassword", targetNamespace = "")
                    String wsPassword,
            @WebParam(name = "wsLanguage", targetNamespace = "")
                    String wsLanguage,
            @WebParam(name = "keys", targetNamespace = "")
                    List<String> keys,
            @WebParam(name = "keyType", targetNamespace = "")
                    int keyType,
            @WebParam(name = "addHistoricalData", targetNamespace = "")
                    boolean addHistoricalData,
            @WebParam(name = "onlyTracking", targetNamespace = "")
                    boolean onlyTracking,
            @WebParam(name = "jsonData", targetNamespace = "")
                    boolean jsonData)
        throws YurticikargoWSException
    ;

    /**
     * 
     * @param returnCode
     * @param wsPassword
     * @param fieldName
     * @param wsUserName
     * @param endDate
     * @param wsLanguage
     * @param maxCount
     * @param startDate
     * @return
     *     returns tr.com.yurticikargo.shippingorderdispatcherservices.ExtendedBaseResultVO
     * @throws YurticikargoWSException
     */
    @WebMethod
    @WebResult(name = "ExtendedBaseResultVO", targetNamespace = "")
    @RequestWrapper(localName = "saveReturnShipmentCode", targetNamespace = "http://yurticikargo.com.tr/ShippingOrderDispatcherServices", className = "tr.com.yurticikargo.shippingorderdispatcherservices.SaveReturnShipmentCode")
    @ResponseWrapper(localName = "saveReturnShipmentCodeResponse", targetNamespace = "http://yurticikargo.com.tr/ShippingOrderDispatcherServices", className = "tr.com.yurticikargo.shippingorderdispatcherservices.SaveReturnShipmentCodeResponse")
    public ExtendedBaseResultVO saveReturnShipmentCode(
            @WebParam(name = "wsUserName", targetNamespace = "")
                    String wsUserName,
            @WebParam(name = "wsPassword", targetNamespace = "")
                    String wsPassword,
            @WebParam(name = "wsLanguage", targetNamespace = "")
                    String wsLanguage,
            @WebParam(name = "fieldName", targetNamespace = "")
                    String fieldName,
            @WebParam(name = "returnCode", targetNamespace = "")
                    String returnCode,
            @WebParam(name = "startDate", targetNamespace = "")
                    String startDate,
            @WebParam(name = "endDate", targetNamespace = "")
                    String endDate,
            @WebParam(name = "maxCount", targetNamespace = "")
                    int maxCount)
        throws YurticikargoWSException
    ;

}
