
package tr.com.yurticikargo.shippingorderdispatcherservices;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "YurticikargoWSException", targetNamespace = "http://yurticikargo.com.tr/ShippingOrderDispatcherServices")
public class YurticikargoWSException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private tr.com.yurticikargo.wsexceptions.YurticikargoWSException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public YurticikargoWSException(String message, tr.com.yurticikargo.wsexceptions.YurticikargoWSException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public YurticikargoWSException(String message, tr.com.yurticikargo.wsexceptions.YurticikargoWSException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: tr.com.yurticikargo.wsexceptions.YurticikargoWSException
     */
    public tr.com.yurticikargo.wsexceptions.YurticikargoWSException getFaultInfo() {
        return faultInfo;
    }

}
